##############################################
#
# General description:
#
#   The following function obtains numeric values of the start 
#   and end of a L1 from a vcf INFO column
#   generated by MELT
#   

# Input:
#
#     x: entry from INFO column in vcf file generated by MELT

# Output:
#   
#     vector of numeric values of the L1 start and end

##############################################

GetFromVcfINFO_MELT_L1StartEnd <- function(x){
  Split1 <- strsplit(x, "%")[[1]]
  Split2 <- Split1[grep("DL1", Split1) + 1:2]
  if (length(Split2)){
    as.numeric(substr(Split2, 3, nchar(Split2)))
  } else {
    c(NA, NA)
  }
  
}
