##############################################
#
# General description:
#
#   The following function obtains a numeric value of the proportion 
#   of a mobile element that differs from consensus from a vcf INFO column
#   generated by MELT
#   

# Input:
#
#     x: entry from INFO column in vcf file generated by MELT

# Output:
#   
#     numeric value of proportion of a mobile that differs from consensus

##############################################

GetFromVcfINFO_MELT_PropDiff <- function(x){
  Split1 <- strsplit(x, ";")[[1]]
  DiffPart1 <- grep("DIFF=", Split1, value = T)
  if (length(DiffPart1) > 0){
    DiffPart2 <- strsplit(DiffPart1, ":")[[1]]
    DiffPart3 <- strsplit(DiffPart2[2], ",")[[1]]
    (length(DiffPart3) - length(grep("n", DiffPart3))) / 
      as.numeric(strsplit(DiffPart2[1], "=")[[1]][2])
  } else {
    NA
  }
}
