# The following script explores error rate results generated by script 
# 'CompareErrorRatesBetwPacBioDatases.R'

# Specify path for plot
PathPlot <- "D:/L1polymORF/Figures/ErrorRateComparison_ErrorRegionsRemoved.pdf"

# Source start script
source('D:/L1polymORFgit/Scripts/_Start_L1polymORF.R')

# Load the results
load("D:/L1polymORF/Data/ErrorComparer_ErrorRegionsRemoved.RData")

# Get ordering of error rates
OrderErrorHiFi      <- order(ErrorHiFi, decreasing = T)
OrderErrorHiFiBWA   <- order(ErrorHiFiBWA, decreasing = T)
OrderErrorNormal    <- order(ErrorNormal, decreasing = T)
OrderErrorNormalBWA <- order(ErrorNormalBWA, decreasing = T)

# Get mean error compared to reference per genomic range
MeanErrorRefHiFi      <- sapply(ErrorRefHiFi, mean)
MeanErrorRefHiFiBWA   <- sapply(ErrorRefHiFiBWA, mean)
MeanErrorRefNormal    <- sapply(ErrorRefNormal, mean)
MeanErrorRefNormalBWA <- sapply(ErrorRefNormalBWA, mean)

OrderErrorRefHiFi      <- order(MeanErrorRefHiFi, decreasing = T)
OrderErrorRefHiFiBWA   <- order(MeanErrorRefHiFiBWA, decreasing = T)
OrderErrorRefNormal    <- order(MeanErrorRefNormal, decreasing = T)
OrderErrorRefNormalBWA <- order(MeanErrorRefNormalBWA, decreasing = T)

# Get genomic ranges with high error rates
GRUnion_withSNP[idxGRHiFi[OrderErrorHiFi[1:10]]]
GRUnion_withSNP[idxGRHiFiBWA[OrderErrorHiFiBWA[1:10]]]
GRUnion_withSNP[idxGRNormal[OrderErrorNormal[1:10]]]
GRUnion_withSNP[idxGRNormalBWA[OrderErrorNormalBWA[1:10]]]

GRUnion_withSNP[idxGRHiFi[OrderErrorRefHiFi[1:10]]]
GRUnion_withSNP[idxGRHiFiBWA[OrderErrorRefHiFiBWA[1:10]]]
GRUnion_withSNP[idxGRNormal[OrderErrorRefNormal[1:10]]]
GRUnion_withSNP[idxGRNormalBWA[OrderErrorRefNormalBWA[1:10]]]

# Plot distribution of error rates
cat("\n***** Writing plot to", PathPlot, "  *****\n")
CountBreaks        <- seq(0, 1, 0.01)
HistErrorHiFi         <- hist(ErrorHiFi,       plot = F, breaks = CountBreaks)
HistErrorHiFiBWA      <- hist(ErrorHiFiBWA,    plot = F, breaks = CountBreaks)
HistErrorNormal       <- hist(ErrorNormal,     plot = F, breaks = CountBreaks)
HistErrorNormalBWA    <- hist(ErrorNormalBWA,  plot = F, breaks = CountBreaks)
HistErrorRefHiFi      <- hist(unlist(ErrorRefHiFi),    plot = F, breaks = CountBreaks)
HistErrorRefHiFiBWA   <- hist(unlist(ErrorRefHiFiBWA), plot = F, breaks = CountBreaks)
HistErrorRefNormal    <- hist(unlist(ErrorRefNormal),  plot = F, breaks = CountBreaks)
HistErrorRefNormalBWA <- hist(unlist(ErrorRefNormalBWA), plot = F, breaks = CountBreaks)

OffSet <- 10^-3
Cols   <- rainbow(2)
YLim   <- c(0, 80)
LX     <- 0.07
LY     <- 60
Lcex   <- 0.75
par(mfrow = c(2, 2), mar = c(3, 2, 2, 1), oma = c(2.5, 2.5, 1, 1.5))
#pdf(file = PathPlot)
plot(HistErrorHiFi$mids - OffSet, HistErrorHiFi$density, type = "s", col = Cols[1],
     xlim = c(0, 0.2), ylim = YLim, xlab = "", ylab = "",
     main = "Betw. ZMWs, nglmr")
lines(HistErrorNormal$mids, HistErrorNormal$density, type = "s", col =  Cols[2])
legend(x = LX, y = LY, legend = c("New polymerase", "Old polymerase"),
       col = Cols, lty = c(1, 1), bty = "n", cex = Lcex)
plot(HistErrorRefHiFi$mids - OffSet, HistErrorRefHiFi$density, type = "s", 
     col = Cols[1], xlim = c(0, 0.2), ylim = YLim, xlab = "", ylab = "",
            main = "Compared to ref., nglmr")
lines(HistErrorRefNormal$mids + OffSet, HistErrorRefNormal$density, type = "s", 
      col =  Cols[2])
legend(x = LX, y = LY, legend = c("New polymerase", "Old polymerase"),
       col = Cols, lty = c(1, 1), bty = "n", cex = Lcex)
plot(HistErrorHiFiBWA$mids - OffSet, HistErrorHiFiBWA$density, type = "s", 
     col = Cols[1], xlim = c(0, 0.2), ylim = YLim,  xlab = "", ylab = "",
     main = "Betw. ZMWs, bwa")
lines(HistErrorNormalBWA$mids, HistErrorNormalBWA$density, type = "s", 
      col =  Cols[2])
legend(x = LX, y = LY, legend = c("New polymerase", "Old polymerase"),
       col = Cols, lty = c(1, 1), bty = "n", cex = Lcex)
plot(HistErrorRefHiFiBWA$mids - OffSet, HistErrorRefHiFiBWA$density, 
     type = "s",  col = Cols[1], xlim = c(0, 0.2), YLim,  xlab = "", ylab = "",
      main = "Compared to ref., bwa")
lines(HistErrorRefNormalBWA$mids + OffSet, HistErrorRefNormalBWA$density, 
      type = "s", col =  Cols[2])
legend(x = LX, y = LY, legend = c("New polymerase", "Old polymerase"),
       col = Cols, lty = c(1, 1), bty = "n", cex = Lcex)
mtext("Error rate", side = 1, line = 1, outer = T)
mtext("Frequency", side = 2, line = 1, outer = T)
CreateDisplayPdf("D:/L1polymORF/Figures/ErrorDistns.pdf",
                 PdfProgramPath = '"C:\\Program Files (x86)\\Adobe\\Reader 11.0\\Reader\\AcroRd32"',
                 height = 7)

#dev.off()
