# The following script explores error rate results generated by script 
# 'CompareErrorRatesBetwPacBioDatases.R'

# Load the results
load("D:/L1polymORF/Data/ErrorComparer.RData")

# Get ordering of error rates
OrderErrorHiFi      <- order(ErrorHiFi, decreasing = T)
OrderErrorHiFiBWA   <- order(ErrorHiFiBWA, decreasing = T)
OrderErrorNormal    <- order(ErrorNormal, decreasing = T)
OrderErrorNormalBWA <- order(ErrorNormalBWA, decreasing = T)

# Get genomic ranges with high error rates
GRUnion_withSNP[idxGRHiFi[OrderErrorHiFi[1:10]]]
GRUnion_withSNP[idxGRHiFiBWA[OrderErrorHiFiBWA[1:10]]]
GRUnion_withSNP[idxGRNormal[OrderErrorNormal[1:10]]]
GRUnion_withSNP[idxGRNormalBWA[OrderErrorNormalBWA[1:10]]]
