#!/bin/bash
#SBATCH --account=dflev
# Set job time to 1 day.
#SBATCH --time=1-00:00:00

# Set a name for the job, visible in `squeue`
#SBATCH --job-name="FindL1RefDel"

# One node.
#SBATCH --nodes=1

# One task
#SBATCH --ntasks=1

# One CPU/core per task
#SBATCH --cpus-per-task=1

# 40GB of RAM
#SBATCH --mem=100G
module load bedtools
bedtools intersect -a $1 -b /labs/dflev/hzudohna/1000Genomes/L1HSRefRanges_Plus200_hg19.bed -wa | \
grep 'SVTYPE=DEL' > $2
echo 'bedtools intersect completed' 
