#!/bin/bash
#SBATCH --account=dflev
# Set job time to 1 day.
#SBATCH --time=6:00:00

# Set a name for the job, visible in `squeue`
#SBATCH --job-name="PairL1GenomeReads"

# One node.
#SBATCH --nodes=1

# One task
#SBATCH --ntasks=1

# One CPU/core per task
#SBATCH --cpus-per-task=1

# 50GB of RAM
#SBATCH --mem=50G

module load samtools
BamFile1=$1
BamFile2=$2
SamFile1=${BamFile1%.bam}.sam
SamFile2=${BamFile2%.bam}.sam
samtools view -o $SamFile1 $BamFile1
samtools view -o $SamFile2 $BamFile2
awk 'BEGIN{print "NAME", "CHROM", "POS", "POSL1"}
  {
        if(NR == FNR){
          if(substr($1, 1, 1) != "#"){ 
          split($1, StArray, "/")
                   POS[StArray[1]] = $4;
          }
        } else {
          split($1, StArray, "/")
          if(substr($1, 1, 1) != "#" && StArray[1] in POS){ 
             print $1, $3, $4, POS[StArray[1]];
          }
        }
    }' $SamFile1 $SamFile2 > $3
